// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1:boolean):Promise<string>;

export function DownloadAndInstallUpdate(arg1:string):Promise<string>;

export function OpenFontFile():Promise<string>;

export function OpenProjectFile():Promise<string>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadFileText(arg1:string):Promise<string>;

export function SaveDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function WriteFileBase64(arg1:string,arg2:string):Promise<void>;

export function WriteFileText(arg1:string,arg2:string):Promise<void>;
