// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdates(arg1) {
  return window['go']['main']['App']['CheckForUpdates'](arg1);
}

export function DownloadAndInstallUpdate(arg1) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1);
}

export function OpenFontFile() {
  return window['go']['main']['App']['OpenFontFile']();
}

export function OpenProjectFile() {
  return window['go']['main']['App']['OpenProjectFile']();
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadFileText(arg1) {
  return window['go']['main']['App']['ReadFileText'](arg1);
}

export function SaveDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveDialog'](arg1, arg2, arg3, arg4);
}

export function WriteFileBase64(arg1, arg2) {
  return window['go']['main']['App']['WriteFileBase64'](arg1, arg2);
}

export function WriteFileText(arg1, arg2) {
  return window['go']['main']['App']['WriteFileText'](arg1, arg2);
}
